columnSuffix: nzmuhnjp
handle: body
instructions: null
name: 'Matrix - Text - Body'
searchable: false
settings:
  advancedLinkFields:
    - target
    - title
    - ariaLabel
  availableTransforms: ''
  availableVolumes:
    - 856a3aeb-b21b-4d41-af3f-0a23db430323 # Bilder
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: 856a3aeb-b21b-4d41-af3f-0a23db430323 # Bilder
  fullGraphqlData: true
  headingLevels:
    - '2'
    - '3'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - underline
    - superscript
    - subscript
    - '|'
    - blockQuote
    - bulletedList
    - numberedList
    - '|'
    - insertImage
    - link
    - '|'
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
